### ISSUE TITLE
Step 1 fails to run

### ISSUE THREAD

**Issue by antonyip** [immutable/imx-examples#6]
Issue tracker is **ONLY** used for reporting bugs.

![image](https://user-images.githubusercontent.com/9086733/142719004-71f8855a-345c-446e-8ae6-82507f5f9ec0.png)
Unable to proceed with instructions as I'm unsure how to proceed with this error.

## Expected Behavior

Account gets registered

## Current Behavior

Script fails to run successfully

## Steps to Reproduce

1. run the command.
2.
3.
4.

## Detailed Description

I've tried private keys with and without 0x prefix.
I've tried adding alchemy keys.
I've tried downgrading axios back to the previous version.
Error doesn't seem to have changed.

**Comment by ipekt** [comment]
hey @antonyip, try following:

1. Make sure you are using either node v12 or v14. We have updated supported versions in [package.json](https://github.com/immutable/imx-examples/blob/main/package.json#L38)
2. Make sure you getting private key from Metamask correctly:  https://metamask.zendesk.com/hc/en-us/articles/360015289632-How-to-Export-an-Account-Private-Key
3. Use most recent examples code

If you still have an issue, please share the error. We added extra logging this error. Hopefully, there will be more details on the console.

**Comment by antonyip** [comment]
@ipekt Resolved. Seems like node.v17 has the issue.
